Repository yannickgloster/discord-10man, pull requests merged in 2020-10, with the labels that each got.

#44 Refactored Code
  bot.py
  checks.py
  cogs/csgo.py
  cogs/setup.py
  cogs/utils.py
  run.py
  utils/csgo_server.py
  utils/server.py
Labels: enhancement

#47 Added Live Match Command
  checks.py
  cogs/csgo.py
  utils/csgo_server.py
  utils/server.py
Labels: enhancement

#58 !link command
  cogs/setup.py
Labels: enhancement

#62 Remove brotlipy
  Pipfile
  Pipfile.lock
  bot.py
  requirements.txt
Labels: bug

#65 Fixed Intents
  bot.py
Labels: fix

#67 Serve files from server
  bot.py
  cogs/csgo.py
  utils/server.py
Labels: enhancement

#68 Gotv embed
  cogs/csgo.py
  utils/csgo_server.py
  utils/server.py
Labels: enhancement

#70 Fixed Bug with Voice Channel Creation
  cogs/csgo.py
Labels: fix

#74 Fixes
  cogs/csgo.py
  cogs/setup.py
  utils/server.py
Labels: fix

#75 Fixed the enabling and disabling of the queue
  bot.py
  cogs/setup.py
Labels: fix

#76 Added Arguments for Pug Command to have random teams and/or map
  bot.py
  cogs/csgo.py
  cogs/setup.py
Labels: enhancement

#77 Automatic Flag for Get5
  bot.py
  cogs/csgo.py
  config_example.json
Labels: enhancement
