Repository yannickgloster/discord-10man, pull requests merged in 2020-11, with the labels that each got.

#78 Added some small features
  bot.py
  cogs/csgo.py
  cogs/utils.py
  utils/server.py
Labels: enhancement

#81 Changed flag logic
  bot.py
  cogs/csgo.py
Labels: enhancement

#82 Added Features Wickerman Requested
  bot.py
  checks.py
  cogs/csgo.py
  cogs/setup.py
Labels: enhancement

#85 Add map veto idle timer
  cogs/csgo.py
Labels: enhancement

#84 Fixes to 1.5.0-beta
  bot.py
  checks.py
  cogs/csgo.py
  cogs/setup.py
  cogs/utils.py
  utils/server.py
Labels: fix

#86 1.6.0
  bot.py
  cogs/csgo.py
  cogs/setup.py
  config_example.json
  utils/server.py
Labels: enhancement, fix

#87 Quick Fixes
  cogs/csgo.py
  utils/server.py
Labels: fix

#93 Small changes
  cogs/csgo.py
  cogs/setup.py
Labels: fix

#94 Fix number of maps in map veto
  utils/veto_image.py
Labels: fix

#99 Fixed Match Sizes
  checks.py
  cogs/csgo.py
Labels: fix

#98 Fix GoTV Ascii Errors
  cogs/csgo.py
  utils/csgo_server.py
Labels: fix

#105 Logging
  .gitignore
  bot.py
  checks.py
  cogs/csgo.py
  cogs/setup.py
  cogs/utils.py
  logging.conf
  utils/csgo_server.py
  utils/server.py
  utils/veto_image.py
Labels: enhancement

#110 Fixed Spectator Bug
  cogs/csgo.py
Labels: fix

#113 Updated json config to be served via the match ID
  cogs/csgo.py
  utils/server.py
Labels: fix
